name: Test Automation Workflow

on:
  schedule:
  - cron: 00 15 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Running Automation Scripts with Maven
      run: mvn clean test -X --Dbrowser=chrome -DisLamdaTest=true -DisHeadless=false


    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
       name: Test Logs
       path: logs/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
       name: Test Reports
       path: ExtentReports/

    - name: Test Execution Status
      run: echo "Test Execution is completed"



    












